name: Build PDF and Create Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4.1.0

      - name: Get current date
        id: date
        run: |
          echo "tag_date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "file_date=$(date +'%B_%Y' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build PDF
        run: typst compile src/main.typ resume_${{ steps.date.outputs.file_date }}.pdf

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: resume_${{ steps.date.outputs.file_date }}.pdf
          tag_name: v${{ steps.date.outputs.tag_date }}
          name: v${{ steps.date.outputs.tag_date }}
          draft: false
          prerelease: false