name: Generate Resume PDFs

on:
  workflow_dispatch:
    inputs:
      send_to:
        description: 'Where to send the generated PDFs?'
        required: true
        type: choice
        options:
          - Release
          - Telegram
        default: 'Release'
      include_phone:
        description: 'Include phone number in PDF?'
        required: true
        type: boolean
        default: false
      use_custom_email:
        description: 'Use custom email instead of default emails?'
        required: true
        type: boolean
        default: false
      custom_email:
        description: 'Custom email to generate resume for'
        required: false
        type: string
        default: ''
      tg_filename:
        description: 'Custom filename for Telegram messages (without extension)'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log workflow inputs
        run: |
          echo "=== Workflow Input Parameters ==="
          echo "Send to: ${{ github.event.inputs.send_to }}"
          echo "Include phone: ${{ github.event.inputs.include_phone }}"
          echo "Use custom email: ${{ github.event.inputs.use_custom_email }}"
          if [ -n "${{ github.event.inputs.custom_email }}" ]; then
            MASKED_EMAIL=$(echo "${{ github.event.inputs.custom_email }}" | sed 's/^[^@]*/****/')
            echo "Custom email: $MASKED_EMAIL"
          else
            echo "Custom email: (not provided)"
          fi
          echo "Telegram filename: ${{ github.event.inputs.tg_filename || '(not provided)' }}"
          echo "==============================="

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Setup Typst
        uses: typst-community/setup-typst@v4.1.0
        with:
          cache-dependency-path: src/main.typ

      - name: Get current date
        id: date
        run: |
          echo "tag_date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          echo "file_date=$(date +'%B_%Y' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build PDFs for all emails
        env:
          RESUME_EMAILS: ${{ vars.RESUME_EMAILS }}
          RESUME_PHONE: ${{ vars.PHONE }}
          TELEGRAM_BOT_TOKEN: ${{ vars.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
        run: |
          if [ "${{ github.event.inputs.use_custom_email }}" == "true" ]; then
            if [ -n "${{ github.event.inputs.custom_email }}" ]; then
              CUSTOM_EMAIL="${{ github.event.inputs.custom_email }}"
            else
              CUSTOM_EMAIL="$RESUME_EMAILS"
            fi
            if [ "${{ github.event.inputs.include_phone }}" == "true" ] && [ -n "$RESUME_PHONE" ]; then
              python3 scripts/generate_resumes.py -e "${CUSTOM_EMAIL}" -p "${RESUME_PHONE}" ${{ github.event.inputs.send_to == 'Telegram' && '-t' || '' }} ${{ github.event.inputs.tg_filename && format('-f {0}', github.event.inputs.tg_filename) || '' }}
            else
              python3 scripts/generate_resumes.py -e "${CUSTOM_EMAIL}" ${{ github.event.inputs.send_to == 'Telegram' && '-t' || '' }} ${{ github.event.inputs.tg_filename && format('-f {0}', github.event.inputs.tg_filename) || '' }}
            fi
          else
            if [ "${{ github.event.inputs.include_phone }}" == "true" ] && [ -n "$RESUME_PHONE" ]; then
              python3 scripts/generate_resumes.py -p "${RESUME_PHONE}" ${{ github.event.inputs.send_to == 'Telegram' && '-t' || '' }} ${{ github.event.inputs.tg_filename && format('-f {0}', github.event.inputs.tg_filename) || '' }}
            else
              python3 scripts/generate_resumes.py ${{ github.event.inputs.send_to == 'Telegram' && '-t' || '' }} ${{ github.event.inputs.tg_filename && format('-f {0}', github.event.inputs.tg_filename) || '' }}
            fi
          fi

      - name: Upload all generated PDFs as artifact
        if: github.event.inputs.include_phone == false
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdfs-${{ steps.date.outputs.tag_date }}
          path: dist/*.pdf
          retention-days: 30

      - name: Create Release
        if: github.event.inputs.send_to == 'Release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.pdf
          tag_name: v${{ steps.date.outputs.tag_date }}
          name: v${{ steps.date.outputs.tag_date }}
          draft: false
          prerelease: false
