name: Create PDF Release

on:
  workflow_dispatch:
    inputs:
      send_to_telegram:
        description: 'Send PDF to Telegram?'
        required: true
        type: boolean
        default: false
      include_phone:
        description: 'Include phone number in PDF?'
        required: true
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Typst
        uses: typst-community/setup-typst@v4.1.0

      - name: Get current date
        id: date
        run: |
          echo "tag_date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT
          echo "file_date=$(date +'%B_%Y' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build PDF
        run: |
          if [ "${{ github.event.inputs.include_phone }}" = "true" ]; then
            typst compile \
              --input phone="${{ vars.PHONE }}" \
              src/main.typ release_${{ steps.date.outputs.file_date }}.pdf
          else
            typst compile \
              src/main.typ release_${{ steps.date.outputs.file_date }}.pdf
          fi

      - name: Create Release
        if: github.event.inputs.send_to_telegram == false
        uses: softprops/action-gh-release@v2
        with:
          files: release_${{ steps.date.outputs.file_date }}.pdf
          tag_name: v${{ steps.date.outputs.tag_date }}
          name: v${{ steps.date.outputs.tag_date }}
          draft: false
          prerelease: false

      - name: Send to Telegram
        if: github.event.inputs.send_to_telegram == 'true'
        run: |
          curl -F document=@release_${{ steps.date.outputs.file_date }}.pdf \
               -F caption="Resume generated on ${{ steps.date.outputs.tag_date }}" \
               "https://api.telegram.org/bot${{ vars.TELEGRAM_BOT_TOKEN }}/sendDocument?chat_id=${{ vars.TELEGRAM_CHAT_ID }}"
