name: Trigger Dependabot

on:
  workflow_dispatch:

permissions:
  security-events: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Dependabot
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ github.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dependabot/alerts 